import numpy as np
import cv2
from scipy.spatial.transform import Rotation as R
from pupil_apriltags import Detector
import rosbag2_py
import os
import glob
import argparse
import json
from rclpy.serialization import deserialize_message
from sensor_msgs.msg import CompressedImage

# Use the custom AprilTag message types generated by arm_v2_description.
from arm_v2_description.msg import AprilTagDetection, AprilTagDetectionArray
from pathlib import Path
import re

"""
Project: Lab Powder Manipulation
File: multitag.py
Author: Liang Yan
Purpose: This script reads raw compressed images stored in rosbag,
         performs AprilTag detections from each sampling time 
         and performs a linear optimization of all detected poses
         to estimate a best-guess camera pose in global frame.
"""


IMAGE_TOPIC = "/webcam/image_raw/compressed"

#Keep these values the same as webcam_apriltag_publisher.py.
TAG_FAMILY = "tag25h9"
TAG_SIZE = 0.04

script_dir = os.path.dirname(os.path.abspath(__file__))
DEFAULT_CALIB_FILE = os.path.normpath(
    os.path.join(script_dir, "..", "..", "config", "camera_calibration.npz")
)

DEFAULT_HANDEYE_FILE = os.path.normpath(
    os.path.join(script_dir, "..", "..", "config", "handeye_result.json")
)

DEFAULT_SYNCED_MSG_TXT = "/home/liangyan/ros2_ws/synced_msg.txt"
if not os.path.exists(DEFAULT_SYNCED_MSG_TXT):
    DEFAULT_SYNCED_MSG_TXT = os.path.normpath(
        os.path.join(script_dir, "synced_msg.txt")
    )


def find_latest_bag_dataset(base_dir="/home/liangyan/ros2_ws"):
    dataset_dirs = sorted(glob.glob(os.path.join(base_dir, "arm_dataset_*")))
    if not dataset_dirs:
        return os.path.join(base_dir, "arm_dataset_missing")
    return dataset_dirs[-1]


#initialize known pose of each AprilTag in the global frame
G_T_tag_dictionary = {
}

#all tags share the same orientation in global frame
G_R_tag = np.array([
    [0, 1,  0],
    [1, 0,  0],
    [0, 0, -1]
])


#the fused G_T_camera pose is expressed in this global frame
GLOBAL_FRAME_ID = "base_link"

max_tag_id = 11
tag_half_size_x = 0.032
tag_half_size_y = 0.029
z_offset = -0.003
num_tags_per_column = 3
num_col = 4
spacing = 0.004
tag_grid_origin_x = 0.39
tag_grid_origin_y = -0.09

def generate_G_T_tag_grid(
    max_tag_id,
    tag_half_size_x,
    tag_half_size_y,
    z_offset,
    num_tags_per_column,
    num_col,
    spacing,
    tag_grid_origin_x,
    tag_grid_origin_y,
):

    tag_coord_dictionary = {}

    for ID in range(max_tag_id+1):
        # Printed output equivalent to MATLAB's "ID" line
        print(ID)

        # y = 2.9 + mod(ID, 3) * (2.9 * 2 + 0.4) cm
        y = tag_half_size_y + (ID % num_tags_per_column) * (tag_half_size_y * 2 + spacing)

        x = np.nan

        # Replaces hardcoded range(1, 5) with range(1, num_col + 1) cm
        for i in range(1, num_col + 1):
            if ID < i * num_tags_per_column:
                # x = 3.2 + (i-1) * (2 * 3.2 + 0.2)
                x = tag_half_size_x + (i - 1) * (2 * tag_half_size_x + spacing)

                if not np.isnan(x):
                    # Plotted point equivalent: x + origin_tag_x, y + origin_tag_y
                    plot_x = x + tag_grid_origin_x
                    plot_y = y + tag_grid_origin_y

                    # Storing coordinates with z_offset in dictionary
                    tag_coord_dictionary[ID] = [plot_x, plot_y, z_offset]

                    break  # Stop checking further columns for this ID so that the inner loop runs once for every ID


    return tag_coord_dictionary



# build the global tag dictionary once, reusing the existing module-level variable
G_T_tag_dictionary = {}

tag_pos_dict = generate_G_T_tag_grid(
    max_tag_id,
    tag_half_size_x,
    tag_half_size_y,
    z_offset,
    num_tags_per_column,
    num_col,
    spacing,
    tag_grid_origin_x,
    tag_grid_origin_y,
)

print("tag_pos_dict =")
print(tag_pos_dict)

for tag_id, pos in tag_pos_dict.items():
    T = np.eye(4)
    T[:3, :3] = G_R_tag
    T[:3, 3] = np.asarray(pos, dtype=np.float64)
    G_T_tag_dictionary[tag_id] = T


def pose_to_T(pose):

    """takes a pose input and convert one ROS geometry_msgs/Pose into a 4x4 homogeneous transformation matrix."""

    #initialize a 4*4 identity matrix
    T = np.eye(4)

    #populate the quaternion parts of the pose into a list
    quaternion = [
        pose.orientation.x,
        pose.orientation.y,
        pose.orientation.z,
        pose.orientation.w
    ]
    
    #convert the quaternion into a rotation matrix using scipy.spatial.transform.Rotation
    T[:3, :3] = R.from_quat(quaternion).as_matrix()

    #populate the translation parts of the pose into the last column of the transformation matrix
    T[:3, 3] = [
        pose.position.x,
        pose.position.y,
        pose.position.z
    ]
    
    return T


def apriltag_detection_to_C_T_tag(detection):

    """
    pupil_apriltags already returns the estimated tag pose as:
        detection.pose_R : 3x3 rotation matrix
        detection.pose_t : 3x1 translation vector

    This function simply converts the estimated pose into a 4x4 homogeneous transformation matrix C_T_tag.
    """
    #simply populating the rotation and translation into a 4x4 homogeneous transformation matrix
    C_T_tag = np.eye(4)
    C_T_tag[:3, :3] = detection.pose_R
    C_T_tag[:3, 3] = np.asarray(detection.pose_t).reshape(3)

    return C_T_tag


def pupil_detection_to_ros_msg(detection):

    """
    Convert one pupil_apriltags detection into an
    arm_v2_description/msg/AprilTagDetection message.
    """

    #create a new AprilTagDetection message
    tag_msg = AprilTagDetection()

    #populate the tag ID, tag size, hamming distance, and decision margin from the pupil_apriltags detection
    tag_msg.tag_id = int(detection.tag_id)
    tag_msg.tag_size = float(TAG_SIZE)
    tag_msg.hamming = int(detection.hamming)
    tag_msg.decision_margin = float(detection.decision_margin)

    #translation of the tag expressed in the camera frame
    tag_msg.pose.position.x = float(detection.pose_t[0][0])
    tag_msg.pose.position.y = float(detection.pose_t[1][0])
    tag_msg.pose.position.z = float(detection.pose_t[2][0])

    #convert the estimated rotation matrix into ROS quaternion order x,y,z,w
    quaternion = R.from_matrix(detection.pose_R).as_quat()

    #populate the quaternion into the ROS message
    tag_msg.pose.orientation.x = float(quaternion[0])
    tag_msg.pose.orientation.y = float(quaternion[1])
    tag_msg.pose.orientation.z = float(quaternion[2])
    tag_msg.pose.orientation.w = float(quaternion[3])

    return tag_msg


def T_to_pose(T):

    """Convert one 4x4 homogeneous transformation matrix into position and quaternion components."""

    #read the translation from the last column of the transformation matrix
    position = T[:3, 3]

    #convert the 3*3 rotation matrix back into a quaternion in ROS order: x, y, z, w
    quaternion = R.from_matrix(T[:3, :3]).as_quat()

    return position, quaternion


def read_tag_poses_from_bag(bag_path, calib_file):

    """
    Pipeline:
        rosbag /webcam/image_raw/compressed
            -> decode each recorded JPEG image
            -> AprilTag detection
            -> AprilTag pose estimation
            -> C_T_tag
            -> G_T_camera candidate
            -> same pose fusion as before

    The rosbag is read sequentially. The next image is not processed until
    detection and pose estimation for the current image have finished, so every
    image that is actually stored in the bag is processed.

    The result keeps the original image header timestamps. Offline processing
    time is never used as the measurement timestamp.
    """

    #load the same camera calibration/intrinsic parameters used by the webcam publisher
    calib_file = Path(calib_file)

    if not calib_file.exists():
        raise FileNotFoundError(
            f"Cannot find camera calibration file: {calib_file}"
        )

    calib = np.load(calib_file)
    camera_matrix = calib["camera_matrix"].astype(np.float64)

    fx = camera_matrix[0, 0]
    fy = camera_matrix[1, 1]
    cx = camera_matrix[0, 2]
    cy = camera_matrix[1, 2]

    camera_params = [fx, fy, cx, cy]

    print(f"Loaded camera calibration: {calib_file}")

    #same detector configuration used by webcam_apriltag_publisher.py
    detector = Detector(
        families=TAG_FAMILY,
        nthreads=2,
        quad_decimate=1.0,
        quad_sigma=0.0,
        refine_edges=1,
        decode_sharpening=0.25,
        debug=0
    )

    #create a rosbag2_py SequentialReader to read the bag file
    reader = rosbag2_py.SequentialReader()

    #set up the storage and converter options for reading the bag (mcap format, no conversion)
    reader.open(
        rosbag2_py.StorageOptions(uri=bag_path, storage_id='mcap'),
        rosbag2_py.ConverterOptions('', '')
    )

    frames = []
    image_count = 0

    while reader.has_next():

        #read one recorded rosbag message
        topic, data, bag_timestamp_ns = reader.read_next()

        #defensive programming: skip any topic that is not the recorded compressed image topic
        #only process the recorded compressed image topic
        if topic != IMAGE_TOPIC:
            continue

        image_count += 1

        #deserialize the bag data into sensor_msgs/CompressedImage
        image_msg = deserialize_message(data, CompressedImage)

        #keep the camera-frame timestamp in rosbag
        stamp_sec = image_msg.header.stamp.sec
        stamp_nanosec = image_msg.header.stamp.nanosec

        image_timestamp_ns = (
            int(stamp_sec) * 1_000_000_000
            + int(stamp_nanosec)
        )

        #decode the JPEG bytes stored in sensor_msgs/CompressedImage
        #this is done by first converting the raw bytes as a numpy array of uint8
        #compressed_image contains the raw bytes of the compressed JPEG image

        compressed_image = np.frombuffer(

            #image_msg.data contains the raw bytes of the compressed image
            image_msg.data,

            #type for JPEG decoding; uint8 is the standard type for image data
            dtype=np.uint8
        )

        frame = cv2.imdecode(

            #parses the raw bytes of the compressed JPEG image and reconstructs the
            #original image as a numpy array of pixels
            compressed_image,

            #load it as a normal color image
            cv2.IMREAD_COLOR
        )

        if frame is None:
            print(
                f"Warning: failed to decode compressed image at "
                f"{stamp_sec}.{stamp_nanosec:09d}"
            )
            continue


        #convert the decoded image to grayscale for AprilTag detection
        gray = cv2.cvtColor(
            frame,
            cv2.COLOR_BGR2GRAY
        )

        #run AprilTag detection and pose estimation offline
        #grayscale image passed to detector
        detections = detector.detect(
            gray,
            estimate_tag_pose=True,
            camera_params=camera_params,
            tag_size=TAG_SIZE
        )

        #build the custom AprilTagDetectionArray message used by the online pipeline
        detections_msg = AprilTagDetectionArray()

        #!NOTICE!: copy the original image header so image and detections have the exact same timestamp
        detections_msg.header = image_msg.header
        detections_msg.number_of_tags_detected = len(detections)
        detections_msg.detections = []

        for detection in detections:
            detections_msg.detections.append(
                pupil_detection_to_ros_msg(detection)
            )

        tag_ids = []
        C_T_tag_array = []
        G_T_camera_array = []
        decision_margins = []
        hammings = []

        #for every detected tag in this image, compute the corresponding G_T_camera pose
        for detection in detections_msg.detections:

            tag_id = int(detection.tag_id)
            tag_ids.append(tag_id)

            #convert the detected ROS pose into C_T_tag:
            #pose of the detected tag expressed in the camera frame
            C_T_tag = pose_to_T(detection.pose)
            C_T_tag_array.append(C_T_tag)

            #look up the known pose of this tag in the global frame and store it in G_T_tag
            if tag_id not in G_T_tag_dictionary:
                print(
                    f"Warning: tag ID {tag_id} is not in "
                    f"G_T_tag_dictionary; using identity G_T_tag for now"
                )
                G_T_tag = np.eye(4)
            else:
                G_T_tag = G_T_tag_dictionary[tag_id]

            #converting C_T_tag to G_T_C using known global tag poses
            #G_T_tag = G_T_camera @ C_T_tag
            #therefore G_T_camera = G_T_tag @ inverse(C_T_tag)
            G_T_camera = G_T_tag @ np.linalg.inv(C_T_tag)
            G_T_camera_array.append(G_T_camera)

            decision_margins.append(float(detection.decision_margin))
            hammings.append(int(detection.hamming))


        #after processing this recorded image, append all the relevant
        #information into the same frame structure used by the fusion code
        #this is to use a consistent format as the fusion logic
        frames.append({
            'timestamp_ns': image_timestamp_ns,
            'G_T_tag_dictionary': G_T_tag_dictionary,
            'bag_timestamp_ns': bag_timestamp_ns,
            'stamp_sec': stamp_sec,
            'stamp_nanosec': stamp_nanosec,
            'frame_id': GLOBAL_FRAME_ID,
            'number_of_tags_detected': detections_msg.number_of_tags_detected,
            'detections_msg': detections_msg,
            'tag_ids': tag_ids,
            'C_T_tag_array': C_T_tag_array,
            'G_T_camera_array': G_T_camera_array,
            'decision_margins': decision_margins,
            'hammings': hammings
        })


        if image_count % 100 == 0:
            print(
                f"Processed {image_count} recorded images "
                f"(latest image: {len(detections)} tag(s))"
            )


    print(
        f"Finished offline AprilTag processing: "
        f"{image_count} recorded images"
    )

    return frames


def reject_outliers(G_T_camera_array, threshold=1.0):
    """
    Rejects input tag poses that are outliers based on their distance from the mean pose. The distance metric is based on the norm of the twist vector obtained from the logarithm map of the relative transformation between each tag pose and the mean pose.
    """
    inliers = []
    translation_errors = []
    rotation_errors = []
    
    for T in G_T_camera_array:
        #calculate the error between the current tag pose and the first tag pose in the array
        T_rel = np.linalg.inv(G_T_camera_array[0]) @ T
        #take the logarithm map of the relative transformation to get the twist vector
        twist = se3_log_map(T_rel)

        #translation error can be quantified by the norm of the linear component of this twist vector
        translation_error = np.linalg.norm(twist[3:])

        #rotation error can be quantified by the norm of the angular component of this twist vector
        rotation_error = np.linalg.norm(twist[:3])
        translation_errors.append(translation_error)
        rotation_errors.append(rotation_error)

    mean_translation_errors = np.mean(translation_errors)
    std_dev_translation_errors = np.std(translation_errors)
    mean_rotation_errors = np.mean(rotation_errors)
    std_dev_rotation_errors = np.std(rotation_errors)

    #for every tag pose, check if its translation and rotation errors are within 2* std dev of errors above the mean
    for T, trans_err, rot_err in zip(G_T_camera_array, translation_errors, rotation_errors):
        if (trans_err <= mean_translation_errors + threshold * 2 * std_dev_translation_errors) and \
           (rot_err <= mean_rotation_errors + threshold * 2 * std_dev_rotation_errors):
            inliers.append(T)
    
    return inliers

def lie_algebra_hat(twist):

    """
    Converts a 6D twist vector [phi, rho] into a 4x4 se(3) Lie algebra matrix.
    phi: 3D angular velocity (rotation vector)
    rho: 3D linear velocity
    """
    phi = twist[:3]
    rho = twist[3:]
    
    # Skew-symmetric matrix for phi
    phi_hat = np.array([
        [0, -phi[2], phi[1]],
        [phi[2], 0, -phi[0]],
        [-phi[1], phi[0], 0]
    ])
    
    Xi = np.zeros((4, 4))
    Xi[:3, :3] = phi_hat
    Xi[:3, 3] = rho

    return Xi

def se3_log_map(T):

    # phi = theta * omega
    # rho = theta * v

    """
    Computes the twist vector [phi,rho]^T from the input of a T.
    Returns: twist vector [phi, rho] of shape (6,)

    Meaning: start from eye(4) and have gotten to T in one unit time, what are
    the constant linear and angular velocities that we have moved with? This is the logarithm map from SE(3) to se(3).
    """
    R_mat = T[:3, :3]
    p = T[:3, 3]
    
    #compute rotation vector phi via Rodrigues/Rotation class

    #build a SciPy rotation object from this matrix
    rot = R.from_matrix(R_mat)

    #converts the rotation object to axis angle vector 3D
    #omega hat: rotational axis; theta: rotational angle; phi = theta * omega_hat
    #R_mat gives these!

    # internally:
    # theta = arccos(trace(R_mat) - 1)/2
    # omega = (omega_1, omega_2, omega_3)
    # omega_1 = (R_mat[3, 2] - R_mat[2, 3]) / (2 * sin(theta))
    # omega_2 = (R_mat[1, 3] - R_mat[3, 1]) / (2 * sin(theta))
    # omega_3 = (R_mat[2, 1] - R_mat[1, 2]) / (2 * sin(theta))
    # omega = (omega_1, omega_2, omega_3)
    # phi = theta * omega_hat
    phi = rot.as_rotvec() #angular velocity vector is solved here

    # theta = mag(phi) = ||phi||, the angle of rotation
    theta = np.linalg.norm(phi)
    

    # rho = theta * v
    # modern robotics 3.88: p = (I*theta + (1-cos(theta))*omega_hat+ (theta - sin(theta))*omega_hat^2)*v
    # modern robotics 3.92: v = (I/theta - 0.5*omega_hat + (1/theta - sin(theta)/(2*(1-cos(theta))))*omega_hat^2)*p
    # for pose estimation, p = V*rho = (I + (1-cos(theta))/theta * omega_hat + (theta - sin(theta))/theta * omega_hat^2)*rho
    # for pose estimation, rho = V_inv*p = (I - 0.5*theta*omega_hat + (1 - theta*sin(theta)/(2*(1-cos(theta))))*omega_hat^2)*p

    if theta < 1e-8:
        # Small angle approximation (Taylor expansion)
        # Build phi_hat (skew-symmetric matrix of phi)
        
        omega = phi / theta if theta > 0 else np.zeros(3)  # Avoid division by zero
        # phi_hat = theta* omega_hat
        axis_hat = np.array([
            [0, -omega[2], omega[1]],
            [omega[2], 0, -omega[0]],
            [-omega[1], omega[0], 0]
        ])

        # with L'Hopital's rule, we can show that as theta -> 0, the inverse left Jacobian V_inv approaches I - 0.5 * phi_hat
        V_inv = np.eye(3) - 0.5 * theta * axis_hat
        rho = V_inv@p

    else:
        # Exact inverse Left-Jacobian V_inv
        omega = phi / theta
        axis_hat = np.array([
            [0, -omega[2], omega[1]],
            [omega[2], 0, -omega[0]],
            [-omega[1], omega[0], 0]
        ])
    
        V_inv = (np.eye(3) - 0.5 * theta * axis_hat +  (1 - (theta * np.sin(theta)) / (2 * (1 - np.cos(theta)))) * np.linalg.matrix_power(axis_hat, 2))
        rho = V_inv@p
        
    return np.hstack((phi, rho))



def se3_exp_map(twist):
    """
    Computes the exponential map exp(twist=S_hat*theta) from 6D vector to SE(3) 4x4 matrix.
    input: twist vector [phi, rho] of shape (6,)
    output: 4x4 SE(3) transformation matrix T

    Meaning: if we start at eye(4) and move with constant linear and angular velocities given by twist for one unit time, where do we end up? This is the exponential map from se(3) to SE(3).
    """

    #for delta t = 1

    # phi = theta * omega
    phi = twist[:3]

    # rho = theta * v
    rho = twist[3:]

    theta = np.linalg.norm(phi)
    
    T = np.eye(4)

    # theta = mag(phi), S = phi/theta, S_hat = skew(phi/theta)
    # rot = eye(3) + sin(theta)*S_hat + (1-cos(theta))*S_hat^2
    rot = R.from_rotvec(phi)
    T[:3, :3] = rot.as_matrix()
    
    # modern robotics 3.88: p = (I*theta + (1-cos(theta))*omega_hat+ (theta - sin(theta))*omega_hat^2)*v
    # modern robotics 3.92: v = (I/theta - 0.5*omega_hat + (1/theta - sin(theta)/(2*(1-cos(theta))))*omega_hat^2)*p
    # for pose estimation, p = V*rho = (I + (1-cos(theta))/theta * omega_hat + (theta - sin(theta))/theta * omega_hat^2)*rho
    # for pose estimation, rho = V_inv*p = (I - 0.5*theta*omega_hat + (1 - theta*sin(theta)/(2*(1-cos(theta))))*omega_hat^2)*p
    if theta < 1e-8:
        #when theta -> 0, p = V*rho = (I + (1-cos(theta))/theta * omega_hat + (theta - sin(theta))/theta * omega_hat^2)*rho
        #                 by L'Hopital's rule, lim theta->0 V = I + sin(theta)*omega_hat + (1-cos(theta))*omega_hat^2 = I
        V = np.eye(3)
    else:
        axis = phi / theta
        axis_hat = np.array([
            [0, -axis[2], axis[1]],
            [axis[2], 0, -axis[0]],
            [-axis[1], axis[0], 0]
        ])
        V = np.eye(3) + ((1.0 - np.cos(theta)) / (theta)) * (axis_hat) + ((theta - np.sin(theta)) / (theta)) * np.linalg.matrix_power(axis_hat, 2)
            
    T[:3, 3] = V @ rho
    return T



def fuse_T_matrix(G_T_camera_array, weights, max_iters=20, tol=1e-6):
    """
    Fuses multiple 4x4 SE(3) pose transformation matrices into a single fused pose.

    
    objective: T_fused = argmin wj*||log(T_fused^{-1} * T_j)||^2 
               to compute a fused pose that minimizes the weighted sum of pose errors relative to all tag poses
               where pose error between the fused pose and the jth tag pose: T_fused * delta_T_j = T_j
               and delta_T_j = T_fused^{-1} * T_j, which can be mapped to scalar by log(e^S_hat*theta) = S_hat*theta, and the norm of the twist vector is a scalar measure of pose error

    cost function: sum_j = wj*||log(T_j^{-1} * T_fused)||^2

    gradient descent: analogous to a cost function of J(x) = sum_j 0.5 * w_j*||x-x_j||^2, we can compute the gradient of the cost function with respect to the fused pose 
                      dJ/dx = sum_j w_j * (x - x_j) = 0, which leads to the weighted average solution x_fused = sum_j w_j * x_j / sum_j w_j
                      gradient descent: x_{k+1} = x_k - alpha * dJ/dx, where alpha is a step size
                      x_{k+1} = x_k - alpha * sum_j w_j * (x_k - x_j) 

                      in SE(3), this is analogous to: T_{k+1} = T_k * exp(-alpha * sum_j w_j * log(T_k^{-1} * T_j)), where exp and log are the exponential and logarithm maps between SE(3) and se(3)
    """
    # 1. Normalize weights to sum to 1
    weights = np.array(weights, dtype=float) / np.sum(weights)
    
    # 2. Initialize with initial guess for fused pose(e.g., first matrix or copy)
    fused_transform = np.copy(G_T_camera_array[0])

    # 3. Iteratively refine the fused pose using weighted tangent-space averaging until corrections are small enough (convergence)
    for iteration in range(max_iters):
        weighted_twist_sum = np.zeros(6)
        
        # for every sample tag pose, compute tangent-space errors relative to current estimate
        for w_j, T_j in zip(weights, G_T_camera_array):
            # Compute relative transformation T_rel = fused_transform^{-1} @ T_j
            T_rel = np.linalg.inv(fused_transform) @ T_j
            
            # Map relative error into the Lie Algebra tangent space (6D twist vector) by taking the logarithm map
            twist_error = se3_log_map(T_rel)
            
            # Accumulate weighted error in tangent space
            weighted_twist_sum += w_j * twist_error
            
        # Check convergence: norm of tangent updates
        if np.linalg.norm(weighted_twist_sum) < tol:
            break
              
        # Retract/Update estimate on the SE(3) manifold: T_new = T_current * exp(delta)
        # Converting the weighted twist error sum back to a homogeneous transformation matrix using the exponential map
        delta_T = se3_exp_map(weighted_twist_sum)

        # Update the fused transformation by composing it with the delta transformation
        fused_transform = fused_transform @ delta_T

    return fused_transform


def fuse_all_frames(frames):

    """Fuse all detected tag poses at every detection timestamp."""

    #for every frame recorded in the rosbag, fuse all the detected tag poses into one fused pose
    for frame in frames:

        #get all G_T_camera estimates computed from the detected tags at this frame
        G_T_camera_array = frame['G_T_camera_array']

        #if no tag was detected at this frame, there is no fused pose
        #frame is a dictionary！
        if len(G_T_camera_array) == 0:
            frame['fused_T'] = None
            continue

        #if only one tag was detected, the fused pose is simply that one G_T_camera estimate at this frame
        if len(G_T_camera_array) == 1:
            frame['fused_T'] = np.copy(G_T_camera_array[0])
            continue

        #reject outliers before fusing; keep only the decision margins that correspond to inlier poses
        inliers = reject_outliers(G_T_camera_array)
        inlier_ids = {id(T) for T in inliers}
        decision_margins = np.array(frame['decision_margins'], dtype=float)
        filtered_poses = [T for T in G_T_camera_array if id(T) in inlier_ids]
        filtered_weights = np.array([w for T, w in zip(G_T_camera_array, decision_margins) if id(T) in inlier_ids])
        G_T_camera_array = filtered_poses

        if len(G_T_camera_array) == 0:
            frame['fused_T'] = None
            continue

        if len(G_T_camera_array) == 1:
            frame['fused_T'] = np.copy(G_T_camera_array[0])
            continue

        #use the AprilTag decision margins as the fusion weights
        #detection margins denote the confidence of the tag detection; a larger decision margin means a more confident detection
        weights = filtered_weights

        #fall back to equal weights if the decision margins are not usable
        if np.sum(weights) <= 0:
            weights = np.ones(len(G_T_camera_array))

        #fuse every G_T_camera estimate at this timestamp into one transformation matrix
        frame['fused_T'] = fuse_T_matrix(G_T_camera_array, weights)

    return frames



def transform_fused_camera_poses_to_gripper(frames, handeye_file):

    """
    Transform the fused camera poses into gripper poses using the hand-eye calibration result.

        Up to this point, tag detection has been run on image_raw inputs, and the resulting
        poses are C_T_tag, which are then converted to G_T_camera using the known G_T_tag poses.

        Therefore, G_T_camera = G_T_tag @ inverse(C_T_tag).

        The hand-eye calibration stores the camera-to-gripper transform, T_camera_gripper.
        Thus, the base-frame gripper pose is:
            G_T_gripper = G_T_camera @ T_camera_gripper

    """

    handeye_file = Path(handeye_file)

    if not handeye_file.exists():
        raise FileNotFoundError(
            f"Cannot find hand-eye calibration file: {handeye_file}"
        )

    with open(handeye_file, "r") as file:
        handeye_result = json.load(file)

    if "camera_to_gripper_matrix" not in handeye_result:
        raise KeyError(
            "hand-eye JSON does not contain 'camera_to_gripper_matrix'"
        )

    gripper_T_camera = np.asarray(
        handeye_result["camera_to_gripper_matrix"],
        dtype=np.float64
    )

    camera_T_gripper = np.linalg.inv(gripper_T_camera)

    if camera_T_gripper.shape != (4, 4):
        raise ValueError(
            "camera_to_gripper_matrix must be a 4x4 homogeneous transform"
        )

    transformed_count = 0

    for frame in frames:

        if frame['fused_T'] is None:
            frame['global_camera_T'] = None
            continue

        # Before this line:
        # frame['fused_T'] = global_T_camera
        global_T_camera = frame['fused_T']

        # Preserve the original fused camera pose.
        frame['global_camera_T'] = np.copy(global_T_camera)

        # Convert the fused camera pose into the gripper pose using the
        # eye-in-hand calibration in the camera->gripper direction.
        frame['fused_T'] = (
            global_T_camera
            @ camera_T_gripper
        )

        transformed_count += 1

    print(
        f"Applied hand-eye transform to {transformed_count} fused poses: "
        f"global_T_gripper = global_T_camera @ T_camera_gripper"
    )

    return frames

def fused_pose_text(frame, indent=''):

    """Convert one fused frame into the ROS-style text format used by the saved pose files."""

    if frame['fused_T'] is None:
        return f"{indent}fused_pose: null\n"

    position, quaternion = T_to_pose(frame['fused_T'])

    return (
        f"{indent}fused_pose:\n"
        f"{indent}  position:\n"
        f"{indent}    x: {position[0]}\n"
        f"{indent}    y: {position[1]}\n"
        f"{indent}    z: {position[2]}\n"
        f"{indent}  orientation:\n"
        f"{indent}    x: {quaternion[0]}\n"
        f"{indent}    y: {quaternion[1]}\n"
        f"{indent}    z: {quaternion[2]}\n"
        f"{indent}    w: {quaternion[3]}\n"
    )



def detections_msg_text(detections_msg):

    """Convert one custom AprilTagDetectionArray message into ROS-style text."""

    text = (
        "detections:\n"
        "  header:\n"
        "    stamp:\n"
        f"      sec: {detections_msg.header.stamp.sec}\n"
        f"      nanosec: {detections_msg.header.stamp.nanosec}\n"
        f"    frame_id: {detections_msg.header.frame_id}\n"
        f"  number_of_tags_detected: {detections_msg.number_of_tags_detected}\n"
    )

    if len(detections_msg.detections) == 0:
        return text + "  detections: []\n"

    text += "  detections:\n"

    for detection in detections_msg.detections:
        text += (
            f"  - tag_id: {detection.tag_id}\n"
            f"    tag_size: {detection.tag_size}\n"
            "    pose:\n"
            "      position:\n"
            f"        x: {detection.pose.position.x}\n"
            f"        y: {detection.pose.position.y}\n"
            f"        z: {detection.pose.position.z}\n"
            "      orientation:\n"
            f"        x: {detection.pose.orientation.x}\n"
            f"        y: {detection.pose.orientation.y}\n"
            f"        z: {detection.pose.orientation.z}\n"
            f"        w: {detection.pose.orientation.w}\n"
            f"    decision_margin: {detection.decision_margin}\n"
            f"    hamming: {detection.hamming}\n"
        )

    return text


def tag_poses_only_text(frame):

    """Convert one frame into a text block that contains only detected tag poses."""

    detections_msg = frame['detections_msg']

    text = (
        "header:\n"
        "  stamp:\n"
        f"    sec: {frame['stamp_sec']}\n"
        f"    nanosec: {frame['stamp_nanosec']}\n"
        f"  frame_id: {detections_msg.header.frame_id}\n"
        f"number_of_tags_detected: {detections_msg.number_of_tags_detected}\n"
    )

    if len(detections_msg.detections) == 0:
        return text + "tag_poses: []\n"

    text += "tag_poses:\n"

    for detection in detections_msg.detections:
        text += (
            f"  - tag_id: {detection.tag_id}\n"
            "    pose:\n"
            "      position:\n"
            f"        x: {detection.pose.position.x}\n"
            f"        y: {detection.pose.position.y}\n"
            f"        z: {detection.pose.position.z}\n"
            "      orientation:\n"
            f"        x: {detection.pose.orientation.x}\n"
            f"        y: {detection.pose.orientation.y}\n"
            f"        z: {detection.pose.orientation.z}\n"
            f"        w: {detection.pose.orientation.w}\n"
        )

    return text


def write_tag_pose_txt(frames, output_path='tag_pose.txt'):

    """Write only detected tag poses for every recorded image."""

    with open(output_path, 'w') as file:
        for frame in frames:
            file.write(tag_poses_only_text(frame))
            file.write("---\n")


def write_fused_pose_txt(frames, output_path='fused_pose.txt'):

    """Write one fused pose for every detection timestamp into fused_pose.txt."""

    with open(output_path, 'w') as file:

        for frame in frames:

            file.write("header:\n")
            file.write("  stamp:\n")
            file.write(f"    sec: {frame['stamp_sec']}\n")
            file.write(f"    nanosec: {frame['stamp_nanosec']}\n")
            file.write(f"  frame_id: {frame['frame_id']}\n")
            file.write(f"number_of_tags_detected: {frame['number_of_tags_detected']}\n")
            file.write(fused_pose_text(frame))
            file.write("---\n")


def insert_offline_results_into_synced_msg_txt(
    frames,
    synced_msg_txt_path,
    output_path='synced_msg_with_fused_pose.txt'
):

    """
    Insert the offline AprilTagDetectionArray and corresponding fused pose into
    each synced message using image_raw.header.stamp as the exact key.

    Because the offline detections come directly from image_raw:
        image_raw.header.stamp
        ==
        detections.header.stamp
        ==
        fused_pose.header.stamp
    """

    frame_by_image_stamp = {
        (frame['stamp_sec'], frame['stamp_nanosec']): frame
        for frame in frames
    }

    def find_frame_for_stamp(stamp_key, max_sec_diff=1):
        """Match the synced-image stamp to the closest offline bag frame.

        Exact matches are preferred, but a small session-to-session clock offset
        can occur between the rosbag and a saved text dump. Accept a near match
        only when it is within a very small time window.
        """
        exact = frame_by_image_stamp.get(stamp_key)
        if exact is not None:
            return exact, 0

        best_frame = None
        best_delta_ns = None

        for frame in frames:
            frame_stamp = (
                int(frame['stamp_sec']),
                int(frame['stamp_nanosec'])
            )
            sec_delta = abs(frame_stamp[0] - stamp_key[0])
            ns_delta = abs(frame_stamp[1] - stamp_key[1])
            total_delta_ns = sec_delta * 1_000_000_000 + ns_delta

            if sec_delta <= max_sec_diff and (best_delta_ns is None or total_delta_ns < best_delta_ns):
                best_delta_ns = total_delta_ns
                best_frame = frame

        if best_frame is None:
            return None, None

        return best_frame, best_delta_ns

    synced_text = Path(synced_msg_txt_path).read_text()

    if not synced_text.strip():
        raise ValueError(
            f"Input synced message text is empty: {synced_msg_txt_path}"
        )


    #splitting the synced message text into blocks separated by "---" allows us to process each message independently
    message_blocks = synced_text.split('---')
    output_blocks = []
    matched_count = 0

    for block in message_blocks:

        # skip any empty blocks that may result from splitting
        if not block.strip():
            continue

        #find image_raw.header.stamp in this synchronized message
        image_stamp = re.search(
            r"(?ms)^image_raw:\n"
            r"  header:\n"
            r"    stamp:\n"
            r"      sec: (\d+)\n"
            r"      nanosec: (\d+)",
            block
        )

        #if there is no image_raw.header.stamp in this block, we cannot match it to any offline detections, so we just keep the original block
        if image_stamp is None:
            output_blocks.append(block.rstrip())
            continue

        stamp_key = (
            int(image_stamp.group(1)),
            int(image_stamp.group(2))
        )

        frame, delta_ns = find_frame_for_stamp(stamp_key)

        if frame is None:
            output_blocks.append(block.rstrip())
            continue

        if delta_ns not in (None, 0):
            print(
                "Using near timestamp match for synced text stamp "
                f"{stamp_key} -> bag stamp ({frame['stamp_sec']}, {frame['stamp_nanosec']}) "
                f"(delta_ns={delta_ns})"
            )

        matched_count += 1

        # Remove any old detections/fused pose block if one was already injected.
        block_without_old_detections = re.sub(
            r"(?ms)^detections:\n.*\Z",
            "",
            block
        ).rstrip()
        block_without_old_detections = re.sub(
            r"(?ms)^fused_pose:\n.*\Z",
            "",
            block_without_old_detections
        ).rstrip()

        # Offline detections generated from this exact image.
        detections_block = detections_msg_text(
            frame['detections_msg']
        ).rstrip()

        # Offline fused camera pose generated from these detections.
        if frame['fused_T'] is None:
            fused_block = "fused_pose: null"
        else:
            position, quaternion = T_to_pose(frame['fused_T'])
            fused_block = (
                "fused_pose:\n"
                "  header:\n"
                "    stamp:\n"
                f"      sec: {frame['stamp_sec']}\n"
                f"      nanosec: {frame['stamp_nanosec']}\n"
                f"    frame_id: {frame['frame_id']}\n"
                "  pose:\n"
                "    position:\n"
                f"      x: {position[0]}\n"
                f"      y: {position[1]}\n"
                f"      z: {position[2]}\n"
                "    orientation:\n"
                f"      x: {quaternion[0]}\n"
                f"      y: {quaternion[1]}\n"
                f"      z: {quaternion[2]}\n"
                f"      w: {quaternion[3]}"
            )

        offline_results = (
            detections_block
            + "\n"
            + fused_block
        )

        # The current synced-message text format does not contain a delta_t_ns field.
        # Append the offline results at the end of each matched block instead.
        block_with_offline_results = (
            block_without_old_detections.rstrip()
            + "\n"
            + offline_results
            + "\n"
        ).rstrip()

        output_blocks.append(block_with_offline_results)

    Path(output_path).write_text(
        "\n---\n".join(output_blocks)
        + "\n---\n"
    )

    if matched_count == 0 and len(output_blocks) > 0:
        text_samples = []
        bag_samples = []

        for block in message_blocks:
            if not block.strip():
                continue
            m = re.search(
                r"(?ms)^image_raw:\n\s*header:\n\s*stamp:\n\s*sec: (\d+)\n\s*nanosec: (\d+)",
                block
            )
            if m is not None:
                text_samples.append((int(m.group(1)), int(m.group(2))))
                if len(text_samples) >= 3:
                    break

        for frame in frames[:3]:
            bag_samples.append((int(frame['stamp_sec']), int(frame['stamp_nanosec'])))

        print(
            "Timestamp match debug: synced_msg text samples = "
            f"{text_samples}, bag frame samples = {bag_samples}"
        )
        raise ValueError(
            "No timestamp matches between offline bag frames and synced_msg text. "
            "This usually means the bag_path and synced_msg.txt come from different "
            "recording sessions. Use the same rosbag as the text dump."
        )

    print(
        f"Matched offline detections/fused poses to "
        f"{matched_count} synced image timestamps"
    )



if __name__ == "__main__":

    parser = argparse.ArgumentParser(
        description=(
            "Offline AprilTag fusion from rosbag images and insertion into synced_msg text"
        )
    )
    parser.add_argument(
        "--bag-path",
        default="/home/liangyan/ros2_ws/arm_dataset_20260816_031556",
        help="Path to rosbag folder that contains /webcam/image_raw/compressed"
    )
    parser.add_argument(
        "--calib-file",
        default=str(DEFAULT_CALIB_FILE),
        help="Path to camera calibration .npz"
    )
    parser.add_argument(
        "--handeye-file",
        default=str(DEFAULT_HANDEYE_FILE),
        help="Path to eye-in-hand hand-eye calibration JSON"
    )
    parser.add_argument(
        "--synced-msg-txt",
        default=DEFAULT_SYNCED_MSG_TXT,
        help="Path to synced message text dump"
    )
    parser.add_argument(
        "--fused-output",
        default="fused_pose.txt",
        help="Output path for fused poses"
    )
    parser.add_argument(
        "--tag-output",
        default="tag_pose.txt",
        help="Output path for per-tag poses"
    )
    parser.add_argument(
        "--synced-output",
        default="synced_msg_with_fused_pose.txt",
        help="Output path for synced message text with offline results"
    )
    args = parser.parse_args()

    #rosbag containing /webcam/image_raw/compressed
    bag_path = args.bag_path

    #camera calibration used for AprilTag pose estimation
    #change this path if camera_calibration.npz is not beside this script
    calib_file = args.calib_file

    #existing text dump of /synced_msg
    synced_msg_txt_path = args.synced_msg_txt


    #read every recorded compressed image from the rosbag,
    #perform AprilTag detection, and then estimate C_T_tag
    frames = read_tag_poses_from_bag(
        bag_path,
        calib_file
    )

    print(f"Processed {len(frames)} recorded image frames")


    #perform one pose fusion independently for all detections in each image
    frames = fuse_all_frames(frames)


    #convert every fused global_T_camera pose into global_T_gripper using:
    #global_T_gripper = global_T_camera @ inverse(gripper_T_camera)
    frames = transform_fused_camera_poses_to_gripper(
        frames,
        args.handeye_file
    )


    #same output as before
    write_fused_pose_txt(
        frames,
        args.fused_output
    )


    #save only per-tag poses from detections for each image timestamp
    write_tag_pose_txt(
        frames,
        args.tag_output
    )


    #same output idea as before, but fused pose is now matched to the
    #source image timestamp instead of an online detections timestamp
    insert_offline_results_into_synced_msg_txt(
        frames,
        synced_msg_txt_path,
        args.synced_output
    )


    print(f"Saved {args.fused_output}")
    print(f"Saved {args.tag_output}")
    print(f"Saved {args.synced_output}")